// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	types "gochat/types"
)

type AuthVerification struct {
	ID     int64              `json:"id"`
	UserID uuid.UUID          `json:"user_id"`
	Type   types.Verification `json:"type"`
	Token  string             `json:"token"`
	Expiry time.Time          `json:"expiry"`
}

type Chatroom struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	CreatorID uuid.UUID `json:"creator_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Dm struct {
	ID           int64     `json:"id"`
	User1ID      uuid.UUID `json:"user1_id"`
	User2ID      uuid.UUID `json:"user2_id"`
	Status       types.DM  `json:"status"`
	CreationDate time.Time `json:"creation_date"`
}

type Message struct {
	ID          int64         `json:"id"`
	Date        time.Time     `json:"date"`
	Text        string        `json:"text"`
	UserID      uuid.UUID     `json:"user_id"`
	ChatroomID  sql.NullInt64 `json:"chatroom_id"`
	DmID        sql.NullInt64 `json:"dm_id"`
	ReplyID     sql.NullInt64 `json:"reply_id"`
	ReplyStatus string        `json:"reply_status"`
}

type Notification struct {
	ID        int64     `json:"id"`
	Message   string    `json:"message"`
	Date      time.Time `json:"date"`
	Link      string    `json:"link"`
	Type      string    `json:"type"`
	Read      bool      `json:"read"`
	UserID    uuid.UUID `json:"user_id"`
	NotifFrom string    `json:"notif_from"`
}

type Setting struct {
	UserID            uuid.UUID `json:"user_id"`
	AcceptsFriendReqs bool      `json:"accepts_friend_reqs"`
	AcceptsDmReqs     bool      `json:"accepts_dm_reqs"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	ProviderID  sql.NullString `json:"provider_id"`
	Username    string         `json:"username"`
	Email       string         `json:"email"`
	Password    sql.NullString `json:"-"`
	JoinDate    time.Time      `json:"join_date"`
	Verified    bool           `json:"verified"`
	Description sql.NullString `json:"description"`
}

type UserJoinedChatroom struct {
	UserID     uuid.UUID `json:"user_id"`
	ChatroomID int64     `json:"chatroom_id"`
	JoinDate   time.Time `json:"join_date"`
}

type UserRelation struct {
	UserID         uuid.UUID          `json:"user_id"`
	RelationUserID uuid.UUID          `json:"relation_user_id"`
	Type           types.UserRelation `json:"type"`
	UpdatedAt      time.Time          `json:"updated_at"`
}
